accounts/urls.py
from django.urls import path
from . import views 


app_name = 'accounts'
urlpatterns = [
    #CR
    path('signup/', views.signup, name='signup'),
    # CR
    path('login/', views.login, name='login'),
    # D
    path('logout/', views.logout, name='logout'),

]

articles/urls.py
from django.urls import path
from . import views


app_name="articles"
urlpatterns = [
    path('',views.index,name='index'),
    path('create/<int:movie_pk>/',views.create,name='create'),
    path('<int:article_pk>/',views.detail,name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
]

game/urls.py
from django.urls import path
from . import views

app_name='game'
urlpatterns = [
    # main 페이지
    path('',views.index,name="index"),
    
    # 메인 게임 
    path('play_game/', views.play_game, name="play_game"),
    # 예고편 보러 가기
    path('<int:game_idx>/',views.movie_detail,name="movie_detail"),
    # 예고편 찜하기
    path('<int:movie_pk>/like/', views.like, name='like'),
    # 찜한 목록 보여주기
    path('my_movie_list/',views.my_movie_list,name="my_movie_list"),
    # 예고편에서 댓글쓰기
    path('<int:poster_idx>/comments/', views.create_comment, name='create_comment'),
    
    # admin용
    path('gameadmin/',views.gameadmin,name="gameadmin"),
    path('movie_update/',views.update_movie,name="update_movie"),

    
]

articles/models.py
from django.db import models
from django.conf import settings
import game.models as game_models
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    movie = models.ForeignKey(game_models.Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label = '',
        widget=forms.TextInput(
            attrs={
                'class':"article-form",
                'placeholder':'Title 입력',
            }
        )
    )
    content = forms.CharField(
        label = '',
        widget=forms.Textarea(
            attrs={
                'class':"article-form",
                'placeholder':'내용입력'
            }
        )
    )
    rating = forms.IntegerField(
        max_value=5,
        min_value=0,
        label = '',
        widget=forms.NumberInput(
            attrs={
                'class':"article-form",
                'placeholder':' 0~5 점수로 평점을 입력해주세요',
            }
        ),
        error_messages={
            'required':'평점을 입력해주세요'
        }
    )
    
    class Meta:
        model = Article
        fields = ['title','content','rating']


class CommentForm(forms.ModelForm):
    
    content = forms.CharField(
        label = '',
        widget=forms.TextInput(
            attrs={
                'class':"comment-create",
                'placeholder':"댓글을 입력하세요"
            }
        )
    )
    
    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ['article', 'user',]

articles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import ArticleForm,CommentForm
from .models import Article, Comment
from game import models as game_models

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods,require_POST,require_GET

from django.db.models import Q

from django.http import JsonResponse
# Create your views here.
def index(request):
    real_articles = Article.objects.all().order_by('-pk')
    
    # 좋아요 많은거 순으로 보여주기!
    rank_data = {}
    for a in real_articles:
        rank_data[a.pk]=len(a.like_user.all())
    rank_data=sorted(rank_data.items(),reverse=True,key=lambda item: item[1])[:8]
    rank_articles = []
    for id,_ in rank_data:
        rank_articles.append(get_object_or_404(Article,pk=id))

    context = {
        'articles1':rank_articles[:4],
        'articles2':rank_articles[4:8],
        'real_articles':real_articles,
    }
    return render(request,'articles/index.html',context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request,movie_pk):
    movie = get_object_or_404(game_models.Movie, pk=movie_pk)
    if request.method=='POST':
        form = ArticleForm(request.POST,request.FILES)
        if form.is_valid():
            article=form.save(commit=False)
            article.user = request.user
            article.movie = movie
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context={
        'form':form,
    }
    return render(request,'articles/form.html',context)


def detail(request,article_pk):
    article = get_object_or_404(Article,pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context={
        'article':article,
        'comment_form': comment_form,
        'comments': comments,
    
    }
    return render(request,'articles/detail.html',context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, article_pk):
    article = get_object_or_404(Article,pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/form.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = Article.objects.get(pk=article_pk)
        if request.user == article.user:
            article.delete()
            return redirect('articles:index')
    return redirect('articles:detail', article.pk)


@require_POST
def create_comment(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article.pk)
    context = {
        'comment_form': comment_form,
        'review': article,
        'comments': article.comment_set.all(),
    }
    return render(request, 'articles/detail.html', context)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)


@require_POST
def like(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        user = request.user
        
        if article.like_user.filter(pk=user.pk).exists():
            article.like_user.remove(user)
            is_like=False
        else:
            article.like_user.add(user)
            is_like=True
        data = {
            'is_like':is_like,
            'like_count': article.like_user.count(),
        }
        return JsonResponse(data)
    return redirect('accounts:login')

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
  {% block css %}
    <link rel="stylesheet" href="{% static 'stylesheets/articles_detail.css' %}">
  {% endblock %}
{% block content %}

<h1 class="text-center mt-3"> 리뷰 </h1>
<div class="row">
  <!--리뷰작성-->
  <div class="col-7">
    <div class="article rounded-top">
      <!--제목 -->
      <div class="row justify-content-between m-0 article-header align-items-center p-1">
        <span>
          {{article.title}}
        </span>
        <span>
          {% if article.updated_at != article.created_at %}
          <span>수정 : {{article.updated_at}}</span>
          {% else %}
          <span>{{article.created_at}}</span>
          {% endif %}
        </span>
      </div>
      <div class="article-content p-1">
        <div class="pt-2">
          {{article.content}}
        </div>
      </div>
      <div class="m-0 line pb-2 d-flex flex-column align-items-center">
        <div>
          {{ article.user }}님의 평점 : <span style="background-color:#005479">{% if article.rating == 1 %}⭐
          {%elif article.rating == 2 %}⭐⭐
          {%elif article.rating == 3 %}⭐⭐⭐
          {%elif article.rating == 4 %}⭐⭐⭐⭐
          {% else %}⭐⭐⭐⭐⭐
          {% endif %}</span>
        </div>
        <div>
          좋아요 : <span id="likeCount-{{article.pk}}" class="d-inline">{{ article.like_user.all|length }}</span>
        </div>
      </div>
      <div class="d-flex justify-content-between">
        <div class="pl-3 pr-3">
          <!-- 좋아요 -->
          <form action="{% url 'articles:like' article.pk %}"method="POST" id="form_like" data-articleId="{{article.pk}}" class="d-inline">
            {% csrf_token %}
            {% if user in article.like_user.all %}
              <button class="btn btn-link" style="box-shadow: none !important;">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill heart-{{article.pk}}" style="color:crimson;" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg>
              </button>
            {% else %}
              <button class="btn btn-link" style="box-shadow: none !important;">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill heart-{{article.pk}}" style="color:black;" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg>
                
              </button>
            {% endif %}
          </form>
        </div>
        {% if request.user == article.user %}
        <div class="row">
          <div class="pl-3 pr-3 d-flex justify-content-center align-items-center">
            <a href="{% url 'articles:update' article.pk %}">수정</a>
          </div>
          <div class="pr-3 d-flex justify-content-center align-items-center">
            <form action="{% url 'articles:delete' article.pk %}" method="POST">
              {% csrf_token %}
              <input class="delete-btn" type="submit" value="DELETE">
            </form>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="comment">
      <h4>댓글 목록</h4>
      {% for comment in comments %}
        <div class="comment-item rounded p-1 d-flex felx-column justify-content-between">
          <div><strong>{{ comment.user }}</strong> - {{ comment.content }}</div>
          <div>
            {% if request.user == comment.user %}
              <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input class="delete-btn pt-0 pb-0" type="submit" value="X">
              </form>
            {% endif %}
          </div>
        </div>
      {% empty %}
        <p><b>댓글이 없어요..</b></p>
      {% endfor %}
      <hr>
      {% if request.user.is_authenticated %}
        <form action="{% url 'articles:create_comment' article.pk %}" method="POST">
          {% csrf_token %}
          {{ comment_form }}
          {% comment %} <input type="submit" class="submit-btn"> {% endcomment %}
        </form>
      {% else %}
      <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
      {% endif %}
    </div>
    <div class="article-footer rounded-bottom">
      <div class="d-flex justify-content-end">
        <div class="pl-3 pr-3">
          <a href="{% url 'articles:index' %}">[back]</a>
        </div>
      </div>
    </div>
  </div>
  <!--영화정보-->
  <div class="col-5 article rounded-top ">
    <div class="d-flex justify-content-center ">
      <div class="col-7">
        <img src="https://image.tmdb.org/t/p/w500/{{article.movie.poster_path}}" alt="" width="100%"> 
      </div>
    </div>
    <div class="movie-content p-2 rounded">
      <div class="d-flex justify-content-between">
        <div>{{article.movie.title}}</div>
        <div>Release : {{article.movie.release_date}}</div>
      </div>
      <br>
      <div>{{article.movie.overview}}</div>
    </div>
  </div>
</div>
{% endblock content %}
{% block script %}
<script>
  const likeBtnForm = document.querySelector('#form_like')
  const articleid =likeBtnForm.dataset.articleid
  console.log(likeBtnForm.dataset)
  console.log(articleid)
  likeBtnForm.addEventListener('click',function (e) {
    e.preventDefault() 
    
    const API_URL = `/articles/${articleid}/like/`
    const csrfToken = document.querySelector('input[name=csrfmiddlewaretoken]').value
    const options = {headers: {'X-CSRFToken': csrfToken}}

    axios.post(API_URL,{},options)
      .then(res => {
        
        const { is_like,like_count } =res.data 
        const likecart = document.querySelector(`.heart-${articleid}`)
        likecart.style.color= is_like ? 'crimson' : 'black'

        const likeCount = document.querySelector(`#likeCount-${articleid}`)
        likeCount.innerText = `${like_count}`
        
      })
      .catch(res => {
        console.log(res.data)
      })
  })
</script>
{% endblock script %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'stylesheets/articles_form.css' %}">
{% endblock %}
{% block content %}
<div style="height:80px;">
  <h1 class="text-center pt-1" style="color:white">📝리뷰 작성</h1>
</div>
<div class="row">
  <form class="form-int col-10" action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      {{form.as_p}}
    </div>
    <button class="submit-btn">Submit!</button>

</div>
</form>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
  {% block css %}
    <link rel="stylesheet" href="{% static 'stylesheets/articles_index.css' %}">
  {% endblock %}
{% block content %}
<!-- 글 목록 나열-->
<section >
  <h1 style="color:white;">커뮤니티</h1>
  <section class="pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-6">
          <h3 class="mb-3 default-text"> 인기글 </h3>
        </div>
        <div class="col-6 text-right" >
          <a class="custom-btn mb-3 mr-1" href="#carouselExampleIndicators2" role="button" data-slide="prev" >
            <i class="fa fa-arrow-left"></i>
          </a>
          <a class="custom-btn mb-3 mr-1" href="#carouselExampleIndicators2" role="button" data-slide="next">
            <i class="fa fa-arrow-right"></i>
          </a>
        </div>
        <div class="col-12">
          <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="row">
                  {% for article in articles1 %}
                  <div class="col-md-3 mb-3 card-height">
                    <div class="card card-height-95">
                      {% comment %} <img class="img-fluid m-auto" alt="100%x280" src="https://image.tmdb.org/t/p/w500/{{article.movie.poster_path}}"> {% endcomment %}
                      <div class="d-flex justify-content-center slide-card-color" style="height:75%">
                        <img class="img-fluid col-10 p-auto" alt="100%x280" src="https://image.tmdb.org/t/p/w500/{{article.movie.poster_path}}" style="height:240px;">
                      </div>
                      <div class="card-body slide-card-color d-flex justify-content-center">
                        <h6 class="card-title col-10 text-center"><a class="default-text" href="{% url 'articles:detail' article.pk %}">{{article.title}}</a></h6>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
              {% if articles2  %}
              <div class="carousel-item">
                  <div class="row">
                    {% for article in articles2 %}
                    <div class="col-md-3 mb-3 card-height">
                      <div class="card card-height-95">
                        {% comment %} <img class="img-fluid" alt="100%x280" src="https://image.tmdb.org/t/p/w500/{{article.movie.poster_path}}"> {% endcomment %}
                        <div class="d-flex justify-content-center slide-card-color" style="height:75%">
                          <img class="img-fluid col-10 p-auto" alt="100%x280" src="https://image.tmdb.org/t/p/w500/{{article.movie.poster_path}}" style="height:100%;">
                        </div>
                        <div class="card-body slide-card-color d-flex justify-content-center">
                          <h6 class="card-title default-text col-10"><a class="default-text" href="{% url 'articles:detail' article.pk %}">{{article.title}}</a></h6>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                    {% comment %} <div class="col-md-4 mb-3">
                      <div class="card">
                        <img class="img-fluid" alt="100%x280" src="https://images.unsplash.com/photo-1532715088550-62f09305f765?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=ebadb044b374504ef8e81bdec4d0e840">
                        <div class="card-body">
                          <h4 class="card-title">Special title treatment</h4>
                          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>

                        </div>
                      </div>
                    </div>
                    <div class="col-md-4 mb-3">
                      <div class="card">
                        <img class="img-fluid" alt="100%x280" src="https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=0754ab085804ae8a3b562548e6b4aa2e">
                        <div class="card-body">
                          <h4 class="card-title">Special title treatment</h4>
                          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>

                        </div>
                      </div>
                    </div> {% endcomment %}
                  </div>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- 여기서부터 최신글 -->
  <div>
    <h2 class="text-white text-center"> 리스트 </h2>
  </div>
  <div class="community-box">
    <div class="row menu_list m-0"> 
      <div class="col-2 text-center">
        <span><b>영화명</b></span>
      </div>
      <div class="col-6 text-center">
        <span><b>제목</b></span>
      </div>
      <div class="col-1 text-center">
        <span><b>평점</b></span>
      </div>
      <div class="col-2 text-center">
        <span><b>작성일</b></span>
      </div>
      <div class="col-1 text-center">
        <span><b>좋아요</b></span>
      </div>
    </div>
    {% for article in real_articles %}
    <div class="row community-item menu_list m-0"> 
      <div class="col-2 d-flex justify-content-center align-items-center">
        <span>{{article.movie.title}}</span>
      </div>
      <div class="col-6 d-flex justify-content-center align-items-center">
        <span class=""><a href="{% url 'articles:detail' article.pk %}">{{article.title}}</a></span>
      </div>
      <div class="col-1 d-flex justify-content-center align-items-center">
        <span>{{article.rating}}</span>
      </div>
      <div class="col-2 d-flex justify-content-center align-items-center">
        <span>{{article.created_at}}</span>
      </div>
      <div class="col-1 d-flex justify-content-center align-items-center">
        <span>{{ article.like_user.all|length }}</span>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
<footer style="height:80px;">
</footer>
  {% comment %} {% for article in articles %}
  <a href="{% url 'articles:detail' article.pk %}">{{article.title}}</a>
  <br>
  {% endfor %}
</section> {% endcomment %}
<!-- 페이지네이션 있으면 좋을듯?-->
{% endblock content %}
{% block script %}


{% endblock script %}