accounts/urls.py
from django.urls import path
from . import views 


app_name = 'accounts'
urlpatterns = [
    #CR
    path('signup/', views.signup, name='signup'),
    # CR
    path('login/', views.login, name='login'),
    # D
    path('logout/', views.logout, name='logout'),

]

articles/urls.py
from django.urls import path
from . import views


app_name="articles"
urlpatterns = [
    path('',views.index,name='index'),
    path('create/<int:movie_pk>/',views.create,name='create'),
    path('<int:article_pk>/',views.detail,name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
]

game/urls.py
from django.urls import path
from . import views

app_name='game'
urlpatterns = [
    # main 페이지
    path('',views.index,name="index"),
    
    # 메인 게임 
    path('play_game/', views.play_game, name="play_game"),
    # 예고편 보러 가기
    path('<int:game_idx>/',views.movie_detail,name="movie_detail"),
    # 예고편 찜하기
    path('<int:movie_pk>/like/', views.like, name='like'),
    # 찜한 목록 보여주기
    path('my_movie_list/',views.my_movie_list,name="my_movie_list"),
    # 예고편에서 댓글쓰기
    path('<int:poster_idx>/comments/', views.create_comment, name='create_comment'),
    
    # admin용
    path('gameadmin/',views.gameadmin,name="gameadmin"),
    path('movie_update/',views.update_movie,name="update_movie"),

    
]

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}base{% endblock %}</title>
  <!-- CSS -->
  {% load static %}
  {% block css %}
  
  {% endblock %}
  <!--favicon-->
  <link rel="shortcut icon"  type="image/png" href="{% static 'stylesheets/favicon.ico' %}">
  <!--글꼴 추가-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap" rel="stylesheet">

  <!--여기 추가-->
  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/ui-lightness/jquery-ui.css">
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/ui-lightness/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
<header class="main-header clearfix" role="header">
  <nav id="menu" class="main-nav" role="navigation">
    <ul class="main-menu">
      <div style="display:inline-block; position:absolute; left:0;">
      <li class="">
      <a href="{%url 'game:index' %}">
      <img src="{% static 'stylesheets/logo.png' %}" alt="logo" width=70px height=80px style="">
      <p style="display:inline-block;">RETRO MOVIE RANDOM GAME</p>
      </a>
      </li>
      </div>
      <!-- 로그인 시 -->
      {% if request.user.is_authenticated %}
      <li class="">
        <a class="" href="{%url 'articles:index'%}">커뮤니티</a>
      </li>
      <li class="">
        <a class="" href="{%url 'game:play_game'%}">게임</a>
      </li>
      <li class="has-submenu"><a href="#section2">{{request.user.username}}</a>
        <ul class="sub-menu">
          {% comment %} <li class="">
            <a class="" href="">Profile</a>
          </li> {% endcomment %}
          <li class="">
            <a class="" href="{%url 'game:my_movie_list'%}">찜한목록</a>
          </li>
          <li class="">
            <a class="text-danger a1" href="{%url 'accounts:logout'%}">로그아웃</a>
          </li>
          {% if request.user.is_staff %}
          <li class="">
            <a class="" href="{%url 'game:gameadmin'%}">DB업뎃</a>
          </li>
          {% endif %}
        </ul>
      </li>
      {% else %}
      <li class="">
        <a class="" href="{%url 'accounts:login'%}">로그인</a>
      </li>
      
      <li class="">
        <a class="" href="{%url 'accounts:signup'%}">회원가입</a>
      </li>
      {% endif %}
      
    </ul>
  </nav>
</header>
  <div style="height:80px;">
  </div>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <div class="underlay-photo"></div>
  <div class="underlay-black"></div>
  <!-- jQuery and JS bundle w/ Popper.js -->
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <!--여기 추가-->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/jquery-ui.min.js"></script>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}
</body>
</html>