accounts/urls.py
from django.urls import path
from . import views 


app_name = 'accounts'
urlpatterns = [
    #CR
    path('signup/', views.signup, name='signup'),
    # CR
    path('login/', views.login, name='login'),
    # D
    path('logout/', views.logout, name='logout'),

]

articles/urls.py
from django.urls import path
from . import views


app_name="articles"
urlpatterns = [
    path('',views.index,name='index'),
    path('create/<int:movie_pk>/',views.create,name='create'),
    path('<int:article_pk>/',views.detail,name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('articles/', include('articles.urls')),
]

game/urls.py
from django.urls import path
from . import views

app_name='game'
urlpatterns = [
    # main 페이지
    path('',views.index,name="index"),
    
    # 메인 게임 
    path('play_game/', views.play_game, name="play_game"),
    # 예고편 보러 가기
    path('<int:game_idx>/',views.movie_detail,name="movie_detail"),
    # 예고편 찜하기
    path('<int:movie_pk>/like/', views.like, name='like'),
    # 찜한 목록 보여주기
    path('my_movie_list/',views.my_movie_list,name="my_movie_list"),
    # 예고편에서 댓글쓰기
    path('<int:poster_idx>/comments/', views.create_comment, name='create_comment'),
    
    # admin용
    path('gameadmin/',views.gameadmin,name="gameadmin"),
    path('movie_update/',views.update_movie,name="update_movie"),

    
]

game/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)


class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField(null=True)
    popularity = models.FloatField(null=True)
    revenue = models.IntegerField(null=True)
    vote_average = models.FloatField(null=True)
    overview = models.TextField(null=True)
    poster_path = models.CharField(null=True,max_length=500)
    genres = models.ManyToManyField(Genre)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')


class MovieComment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


class TempMovie(models.Model):
    movie_id = models.IntegerField()
    poster_idx = models.IntegerField()

game/forms.py
from django import forms
from .models import Movie,MovieComment

class CommentForm(forms.ModelForm):
    
    content = forms.CharField(
        label = '',
        widget=forms.TextInput(
            attrs={
                'class':"my-content form-control2 ",
                
            }
        )
    )
    class Meta:
        model = MovieComment
        # fields = '__all__'
        exclude = ['movie', 'user',]

game/views.py
# 영화 
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie,Genre,TempMovie
from articles import models as articles_models

from .forms import CommentForm

import random
import requests
from bs4 import BeautifulSoup

from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods,require_POST,require_GET

# 게임
import random 


# Create your views here.
def gameadmin(request):
    if request.user.is_staff:
        return render(request,'game/gameadmin.html')
    else:
        return render(request,'game/index.html')


def index(request):
    movies = Movie.objects.all()
    random_movie = random.choice(list(movies))
    context={
        'random_movie':random_movie,
    }
    return render(request,'game/index.html',context)


# 게임 페이지로 넘어가는 함수 
@login_required
def play_game(request):
    tempmovieall = TempMovie.objects.all()
    tempmovieall.delete()
    total = []
    num = [i for i in range(1,449)]
    # 중복없이 10개 뽑기
    randomNum = random.sample(num, 10)
    # print(randomNum)
    for idx,i in enumerate(randomNum) :
        getMovie = Movie.objects.get(id=i)
        TempMovie.objects.create(poster_idx=idx,movie_id=getMovie.id)
        total.append(getMovie)
    context = {
        'movies': total,
    }

    return render(request, 'game/play_game.html', context)


# 예고편 보러가기
@login_required
def movie_detail(request,game_idx):
    tempmovie = get_object_or_404(TempMovie,poster_idx=game_idx)
    movie_pk = tempmovie.movie_id
    movie = get_object_or_404(Movie,pk=movie_pk)
    # youtube API_KEY
    API_KEYS=[
        'AIzaSyBHMW3H4EmxroW7qAhTbVto52JrCnUHx1E'
        'AIzaSyCa5YwT7EcLVanemRFiNHhpyVy64sKu7Dw',
        'AIzaSyClauhHokVFylfo5bKnc80LTnNuurpC1O8',
        'AIzaSyCdneHhIhINFW9826nIXk0OJVtSnCq_aI8',
        'AIzaSyDthd4UCpNEiZIDddiTZZNQjxDlfsLHvc8',
    ]
   
    ## 예고편 가져오기1 TMDB에서!!
    
    # TMDB에서 영화 ID 찾기
    API_KEY = 'be806e5cce014657ffa0b51002fc8512'
    url = 'https://api.themoviedb.org/3/search/movie?api_key='+API_KEY+'&language=ko-KR&query='+movie.title+'&page=1&include_adult=false'
    res = requests.get(url)
    # movie_dict안에 영화 아이디가 있어요.
    movie_dict = res.json()
    movie_id = (movie_dict.get('results')[0].get('id'))

    # TMDB에서 영화 ID 기반으로 예고편 YOUTUBE ID 찾기
    url = 'https://api.themoviedb.org/3/movie/'+str(movie_id)+'/videos?api_key='+API_KEY+'&language=ko-KR'
    res = requests.get(url)
    movie_detail = res.json()
    if len(movie_detail.get('results')):
        youtube_id = movie_detail.get('results')[0].get('key')
        youtube = 'https://www.youtube.com/embed/'+str(youtube_id)+'?autoplay=1'
        print('tmdb')
    
    ## 예고편 가져오기1 YOUTUBE에서!!
    else:
        # TMDB에 영화 예고편 YOUTUBE ID 정보가 없다면 유투브에서 직접 검색해보기
        URL = 'https://www.googleapis.com/youtube/v3/search'
        for idx,API_KEY in enumerate(API_KEYS):
            params= {
                'part': 'snippet',
                'key': API_KEY,
                'q': movie.title +' 예고편',
            }
            res = requests.get(URL, params=params)
            youtube_result=res.json()

            # 유툽 API_KEY 할당량이 다 끝나서 더이상 검색해줄 수 없을 때, error 페이지로 넘어가기
            if youtube_result.get('items',0)!=0:
                print('youtube!')
                youtube_id = youtube_result['items'][0].get('id')['videoId']
                youtube = 'https://www.youtube.com/embed/'+str(youtube_id)+'?autoplay=1'
                break

            # 유툽에서 정상적으로 정보를 가져오면 그거 뿌려주기!
            else:
                if idx==len(API_KEYS)-1:
                    print(idx,'아무대서도 받아오지 못했어요')
                    return render(request,'game/error.html')
    
    # 댓글 가져오기
    comments = movie.moviecomment_set.all()
    comment_form = CommentForm()

    context = {
        'youtube':youtube,
        'movie':movie,
        'comment_form': comment_form,
        'comments': comments,
        'poster_idx': tempmovie.poster_idx
    }
    return render(request,'game/movie_detail.html',context)


# # 영화 찜하기
@require_POST
def like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie,pk=movie_pk)
        user = request.user

        if movie.like_user.filter(pk=user.pk).exists():

            movie.like_user.remove(user)
            is_like = False
        else:
            movie.like_user.add(user)
            is_like = True

        data = {
            'is_like':is_like,
            'like_count': movie.like_user.count(),
        }  
        return JsonResponse(data)
    return redirect('accounts:login')


# 영화 댓글 쓰기
@require_POST
def create_comment(request, poster_idx):
    tempmovie = get_object_or_404(TempMovie,poster_idx=poster_idx)
    movie_pk = tempmovie.movie_id
    movie = get_object_or_404(Movie,pk=movie_pk)

    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.movie = movie
        comment.user = request.user
        comment.save()
        return redirect('game:movie_detail', poster_idx)
    context = {
        'comment_form': comment_form,
        'review': movie,
        'comments': movie.moviecomment_set.all(),
    }
    return render(request, 'game/movie_detail.html', context)


# 찜한 목록!!
def my_movie_list(request):
    user = request.user
    movies=user.like_movies.all()
    # writen_articles = get_object_or_404(articles_models.Article,pk=user.id)

    context={
        'movies':movies
    }
    return render(request,'game/my_movie_list.html',context)


def update_movie(request):

    # movie_list : 네이버 평점 순 500개 영화 제목 저장할 리스트!
    movie_list=[]
    number=11
    for i in range(1,number):
        URL = 'https://movie.naver.com/movie/sdb/rank/rmovie.nhn?sel=pnt&date=20201118&page='

        req = requests.get(URL+str(i))
        html = req.text
        soup = BeautifulSoup(html, 'html.parser')
        ## CSS Selector를 통해 html요소들을 찾아낸다.
        my_titles = soup.select(
            ' td.title > div > a'
            )

        for title in my_titles:
            ## Tag안의 텍스트
            movie_list.append(title.get('title'))

    ## DB에 데이터 넣기
    API_KEY = 'be806e5cce014657ffa0b51002fc8512'
    for movie_title in movie_list:
        # tmdb에선 영화 정보를 찾으려면, 영화 아이디가 있어야함. 그래서 영화 아이디 찾기 위한 코드
        url = 'https://api.themoviedb.org/3/search/movie?api_key='+API_KEY+'&language=ko-KR&query='+movie_title+'&page=1&include_adult=false'
        res = requests.get(url)
        # movie_dict안에 영화 아이디가 있어요.
        movie_dict = res.json()

        # 그런데 영화 아이디가 존재하지 않는 경우가 발생했음! 그래서 그런 오류가 발생할 때를 대비해서
        # try / except 문법사용
        try:
            
            movie_id = (movie_dict.get('results')[0].get('id'))
            url = 'https://api.themoviedb.org/3/movie/'+str(movie_id)+'?api_key='+API_KEY+'&language=ko-KR'
            res = requests.get(url)

            # movie_detail에 내가 원하는 영화 정보가 들어있다!!
            movie_detail = res.json()

            # 본격적으로 우리가 가진 DB에 데이터 집어 넣기!
            # models.py에 정의한 Movie 가져와서 movie1 오브젝트 만들기
            movie1 = Movie(title=movie_title)
            
            import datetime
            # 모델링한 필드에 맞게 데이터 넣어주기
            movie1.release_date=datetime.datetime.strptime(movie_detail.get('release_date'),'%Y-%m-%d')
            movie1.popularity=movie_detail.get('popularity')
            movie1.revenue=movie_detail.get('revenue')
            movie1.vote_average=movie_detail.get('vote_average')
            movie1.overview=movie_detail.get('overview')
            movie1.poster_path=movie_detail.get('poster_path')

            # 디비에 저장!
            movie1.save()

            # manytomany field는 다음과 같이 .add를 해서 넣어줘야한다고 공식문서에 나와있어서, 이대로 함!
            for g in movie_detail.get('genres'):
                genre_id = g.get('id')
                movie1.genres.add(Genre.objects.get(id=genre_id))
            
            print(movie1)
        except:
            continue
    context={
        'movies':Movie.objects.all()
    }
    # 영화 업데이트했으면 그 결과 보는 페이지 하나 만들었어요.
    return render(request,'game/update_movie.html',context)







    '''
    ##영화 네이버 api 검색 후 DB에 저장
    for movie_tite in movie_list:
        keyword = director+' '+title
        client_id = "9iYbqEfGQkmbMGaqjtwk"
        client_secret = "o9q41jvoQy"
        url = "https://openapi.naver.com/v1/search/movie.json?query=" + keyword # json 결과
        result = requests.get(urlparse(url).geturl(),
                        headers={"X-Naver-Client-Id":client_id,
                                "X-Naver-Client-Secret":client_secret})
        movie_dict = result.json()
    print(movie_dict.get('items')[0])
    print(movie_dict.get('items')[0].get('image'))
    print(movie_dict.get('items')[0].get('director').split('|'))
    print(movie_dict.get('items')[0].get('actor').split('|'))


    

    # tmdb
    API_KEY = 'be806e5cce014657ffa0b51002fc8512'
    url = 'https://api.themoviedb.org/3/search/movie?api_key='+API_KEY+'&language=ko-KR&query='+keyword+'&page=1&include_adult=false'
    res = requests.get(url)
    movie_dict = res.json()
    movie_id = (movie_dict.get('results')[0].get('id'))

    print(movie_id)
    url = 'https://api.themoviedb.org/3/movie/'+str(movie_id)+'?api_key='+API_KEY+'&language=ko-KR'
    res = requests.get(url)
    movie_img = res.json()
    print(movie_img)
    '''

game/templates/game/gameadmin.html
{% extends 'base.html' %}
{% load static %}
  {% block css %}
    <link rel="stylesheet" href="{% static 'stylesheets/game_gameadmin.css' %}">
  {% endblock %}

{% block content %}
<div class="error-page">
  <div class="d-flex flex-column justify-content-center align-items-center mt-3" style="margin-top:5rem;">
    <div class="d-flex flex-column justify-content-center align-items-center comment">
      <svg width="5em" height="5em" viewBox="0 0 17 16" class="bi bi-exclamation-triangle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 5zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
      </svg>
      <div>영화 데이터 셋을 업데이트할 때! 눌러주세요</div>
    </div>
    <form action="{% url 'game:update_movie' %}">
      {% csrf_token %}
      <button class="delete-btn">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cloud-download" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M4.406 1.342A5.53 5.53 0 0 1 8 0c2.69 0 4.923 2 5.166 4.579C14.758 4.804 16 6.137 16 7.773 16 9.569 14.502 11 12.687 11H10a.5.5 0 0 1 0-1h2.688C13.979 10 15 8.988 15 7.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 2.825 10.328 1 8 1a4.53 4.53 0 0 0-2.941 1.1c-.757.652-1.153 1.438-1.153 2.055v.448l-.445.049C2.064 4.805 1 5.952 1 7.318 1 8.785 2.23 10 3.781 10H6a.5.5 0 0 1 0 1H3.781C1.708 11 0 9.366 0 7.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383z"/>
          <path fill-rule="evenodd" d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"/>
        </svg>
        업데이트!
      </button>
  </div>
</div>
</form>
{% endblock content %}

game/templates/game/index.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'stylesheets/index.css' %}">
{% endblock %}

{% block title%}
  home
{% endblock%}


{% block content %}
<div class="my-container">
  <h1>싸피가~좋아하는~랜덤~게임!🎰</h1>
  <img src="{% static 'stylesheets/play.gif' %}" alt="실행화면" class="play-img">
  {% if request.user.is_authenticated %}
  <div class="login-form1">
    <a href="{% url 'game:play_game' %}">
      <button>게임 시작하기</button>
    </a>
  </div>
  {% else %}
  <div class="login-form1">
    <a href="{% url 'accounts:login' %}">
      <button>로그인 후 사용하기</button>
    </a>
  </div>
  {% endif %}
</div>
{% endblock%}

game/templates/game/movie_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'stylesheets/moviedetail.css' %}">
{% endblock %}

{% block title %}
movie detail
{% endblock %}
{% block content %}
<div class="my-container">
  <div class="">
    <div 영화 class="movie-title">
        ✨영화 제목 : {{movie.title}}
    </div>
    <div class="col-md-6 align-self-center">
      <div>
        <iframe id="frame" src="{{youtube}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" height="315px;" allowfullscreen></iframe>
      </div>
    </div>
  </div>
  <!-- 장바구니 -->
  <div class="shopping-basket">
    <div>
      <form action="{% url 'game:like' movie.pk %}"method="POST" id="form_like" data-movieId="{{movie.pk}}" class="d-inline">
        {% csrf_token %}
        {% if user in movie.like_user.all %}
          <button class="btn btn-link " style="box-shadow: none !important;">
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-cart-check-fill cart-{{movie.pk}}"  style="color:#f5a302;" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM4 14a1 1 0 1 1 2 0 1 1 0 0 1-2 0zm7 0a1 1 0 1 1 2 0 1 1 0 0 1-2 0zm.354-7.646a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
            </svg>
          </button>
        {% else %}
          <button class="btn btn-link " style="box-shadow: none !important;">
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-cart-check-fill cart-{{movie.pk}}"  style="color:white;" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM4 14a1 1 0 1 1 2 0 1 1 0 0 1-2 0zm7 0a1 1 0 1 1 2 0 1 1 0 0 1-2 0zm.354-7.646a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
            </svg>
          </button>
        {% endif %}
      </form>
      <span id="likeCount-{{movie.pk}}" class="d-inline">{{ movie.like_user.all|length }}</span> 명이 찜했습니다.
    </div>
  </div>
  <!-- 댓글  -->
  <div class="comment">
    <div class="comment-list">
      <h4>댓글 목록</h4>
      {% if comments|length %}
        <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
      {% endif %}
      {% for comment in comments %}
        <div>
          {{ comment.user }} - {{ comment.content }}
        </div>
      {% empty %}
        <p><b>댓글이 없어요..</b></p>
      {% endfor %}
    </div>
      <hr>
      <div class="container row">
        <div class="col-10">
          <form action="{% url 'game:create_comment' poster_idx %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
          </div>
          <button class="btn-2 button col-2">댓글 작성</button>
        </form>
      <div>
  </div>
</div>
{% endblock content %}

{% block script %}


<script>
  
  const likeBtnForm = document.querySelector('#form_like')
  const movieId =likeBtnForm.dataset.movieid
  console.log(likeBtnForm.dataset)
  console.log(movieId)
  likeBtnForm.addEventListener('click',function (e) {
    e.preventDefault() 
    
    const API_URL = `/${movieId}/like/`
    const csrfToken = document.querySelector('input[name=csrfmiddlewaretoken]').value
    const options = {headers: {'X-CSRFToken': csrfToken}}

    axios.post(API_URL,{},options)
      .then(res => {
        
        const { is_like,like_count } =res.data 
        const likecart = document.querySelector(`.cart-${movieId}`)
        likecart.style.color= is_like ? '#f5a302' : 'white'

        const likeCount = document.querySelector(`#likeCount-${movieId}`)
        likeCount.innerText = `${like_count}`
        
      })
      .catch(res => {
        console.log(res.data)
      })
  })

</script>
{% endblock script %}

game/templates/game/my_movie_list.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'stylesheets/game_mymovielist.css' %}">
{% endblock %}

{% block content %}
<h1 class="text-center text-white">📚찜한 목록</h1>
  <div class="row d-flex">
  {% for movie in movies %}
    <div class="col-4 mt-3 card-box">
      <div class="col-12 card-content" style="height:80%">
        
        <div class="pt-2"> 
          <img src="https://image.tmdb.org/t/p/w500/{{movie.poster_path}}" alt="포스터" width="100%" height="360px;">
        </div>
          <!--모달-->
        <div class="card-text d-flex justify-content-center algin-items-center"><a href="" data-toggle="modal" data-target="#postModal-{{ movie.id }}">{{movie.title}}</a></div>
        <div class="modal fade" id="postModal-{{ movie.id }}" tabindex="-1" aria-labelledby="postModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content flex-row">
              <div class="col-8 p-0">
                <img class="card-img" src="https://image.tmdb.org/t/p/w500/{{movie.poster_path}}" alt="포스터" width="315px">
              </div>
              <div class="col">
                <div class="modal-body">
                  <span>
                    {{movie.title}}
                  </span>
                  <br>
                  <span>
                    평점 : {{movie.vote_average}}
                  </span>
                </div>
                <div class="modal-footer d-flex flex-column align-items-center justify-content-end">
                  <div>
                    <a href="https://serieson.naver.com/search/search.nhn?t=all&fs=movie&q={{movie.title}}" target="_blank">영화보기</a>
                  </div>
                  <div>
                    <a href="{%url 'articles:create' movie.id %}">후기쓰기</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% comment %} <!--임시-->
    <div class="col-4 mt-3  card-box">
      <div class="col-12 card-content" style="height:80%">
        
        <div class="pt-2"> 
          <img src="https://image.tmdb.org/t/p/w500/{{movie.poster_path}}" alt="포스터" width="100%" height="80%">
        </div>
          <!--모달-->
        <div class="card-text d-flex justify-content-center algin-items-center"><a href="" data-toggle="modal" data-target="#postModal-{{ movie.id }}">{{movie.title}}</a></div>
        <div class="modal fade" id="postModal-{{ movie.id }}" tabindex="-1" aria-labelledby="postModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content flex-row">
              <div class="col-8 p-0">
                <img class="card-img" src="https://image.tmdb.org/t/p/w500/{{movie.poster_path}}" alt="포스터" width="315px">
              </div>
              <div class="col">
                <div class="modal-body">
                  <span>
                    {{movie.title}}
                  </span>
                  <br>
                  <span>
                    평점 : {{movie.vote_average}}
                  </span>
                </div>
                <div class="modal-footer d-flex flex-column align-items-center justify-content-end">
                  <div>
                    <a href="https://serieson.naver.com/search/search.nhn?t=all&fs=movie&q={{movie.title}}" target="_blank">영화보기</a>
                  </div>
                  <div>
                    <a href="{%url 'articles:create' movie.id %}">후기쓰기</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-4 mt-3  card-box">
      <div class="col-12 card-content" style="height:80%">
        
        <div class="pt-2"> 
          <img src="https://image.tmdb.org/t/p/w500/{{movie.poster_path}}" alt="포스터" width="100%" height="80%">
        </div>
          <!--모달-->
        <div class="card-text d-flex justify-content-center algin-items-center"><a href="" data-toggle="modal" data-target="#postModal-{{ movie.id }}">{{movie.title}}</a></div>
        <div class="modal fade" id="postModal-{{ movie.id }}" tabindex="-1" aria-labelledby="postModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content flex-row">
              <div class="col-8 p-0">
                <img class="card-img" src="https://image.tmdb.org/t/p/w500/{{movie.poster_path}}" alt="포스터" width="315px">
              </div>
              <div class="col">
                <div class="modal-body">
                  <span>
                    {{movie.title}}
                  </span>
                  <br>
                  <span>
                    평점 : {{movie.vote_average}}
                  </span>
                </div>
                <div class="modal-footer d-flex flex-column align-items-center justify-content-end">
                  <div>
                    <a href="https://serieson.naver.com/search/search.nhn?t=all&fs=movie&q={{movie.title}}" target="_blank">영화보기</a>
                  </div>
                  <div>
                    <a href="{%url 'articles:create' movie.id %}">후기쓰기</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> {% endcomment %}
  {% endfor %}
  </div>
{% endblock content %}

game/templates/game/update_movie.html
{% extends 'base.html' %}

{% block content %}
<h1>업데이트완료!</h1>
{% for movie in movies %}
<p>{{movie.title}}</p>
{% endfor %}
{% endblock content %}